name: Deploy

on:
  push:
    branches: [ master ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Run unit tests
        run: yarn test:unit
        
      - name: Build
        run: yarn build
        
      - name: SSH Connection
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          source: "., !node_modules"
          target: "app"
          
      - name: Run multiple commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          script: |
            cd ./app
            yarn
            yarn build
            yarn prisma migrate deploy
            yarn prisma generate
            pm2 restart kaguya

 
